# Generated by Django 5.2.1 on 2025-05-11 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "stripe_price_id",
                    models.CharField(max_length=100, verbose_name="Stripe Price ID"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Yearly")],
                        default="month",
                        max_length=10,
                        verbose_name="Billing Period",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("stripe_customer_id", models.CharField(max_length=100, unique=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="subscriptio_email_1fc610_idx"),
                    models.Index(
                        fields=["is_active"], name="subscriptio_is_acti_6b04ba_idx"
                    ),
                    models.Index(
                        fields=["plan"], name="subscriptio_plan_id_2fe586_idx"
                    ),
                ],
            },
        ),
    ]
