# Generated by Django 5.2.1 on 2025-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
